<a href="https://colab.research.google.com/github/ramandeepm0014/Superstore-Data-Analysis/blob/main/Sample_Superstore_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
('/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv')

'/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv'

In [ ]:
import pandas as pd
pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv')

,Row ID,Order ID,Order Date,Ship Date,Customer Name,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Darren Powers,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,FURNITURE,Bookcases,261.960,2,0.00,41.9136
1,2,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Consumer,United States,Henderson,Kentucky,42420,south,Furniture,Chairs,731.940,3,0.00,219.5820
2,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
3,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310
4,5,US-2023-141817,01-05-2023,01-12-2023,Mick Brown,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,794,US-2023-127691,7/22/2023,7/27/2023,Erin Mull,Standard Class,Consumer,United States,San Francisco,California,94110,West,Office Supplies,Labels,9.960,2,0.00,4.5816
1003,575,US-2023-141299,06-03-2023,06-07-2023,Ross Baird,Standard Class,Consumer,United States,Marysville,Washington,98270,West,Office Supplies,Art,8.820,3,0.00,2.3814
1004,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
1005,262,US-2023-141838,3/26/2023,3/31/2023,Damala Kotsonis,Standard Class,Corporate,United States,Pasadena,Texas,77506,central,Office Supplies,Appliances,1.624,2,0.80,-4.4660
1006,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Customer Name,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Darren Powers,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,FURNITURE,Bookcases,261.960,2,0.00,41.9136
1,2,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Consumer,United States,Henderson,Kentucky,42420,south,Furniture,Chairs,731.940,3,0.00,219.5820
2,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
3,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310
4,5,US-2023-141817,01-05-2023,01-12-2023,Mick Brown,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.20,2.5164

In [ ]:
df.shape

(1007, 18)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Customer Name',
       'Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1007 non-null   int64
 1   Order ID       1005 non-null   object
 2   Order Date     1007 non-null   object
 3   Ship Date      1007 non-null   object
 4   Customer Name  1002 non-null   object
 5   Ship Mode      1007 non-null   object
 6   Segment        1007 non-null   object
 7   Country        1007 non-null   object
 8   City           1006 non-null   object
 9   State          1005 non-null   object
 10  Postal Code    1007 non-null   int64
 11  Region         1007 non-null   object
 12  Category       1007 non-null   object
 13  Sub-Category   1007 non-null   object
 14  Sales          1005 non-null   float64
 15  Quantity       1007 non-null   int64
 16  Discount       1007 non-null   float64
 17  Profit         1006 non-null   float64
dtypes: float64(3), int64(3), object(12)
memory usage: 141.7+ KB

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         2
Order Date       0
Ship Date        0
Customer Name    5
Ship Mode        0
Segment          0
Country          0
City             1
State            2
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            2
Quantity         0
Discount         0
Profit           1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(6)

In [ ]:
df['Region'].unique()

array(['South', 'south', 'West', 'WEST', 'Central', 'East', 'EAST',
       'central', 'SOUTH', 'west'], dtype=object)

In [ ]:
df['Category'].unique()

array(['FURNITURE', 'Furniture', 'Office Supplies', 'OFFICE SUPPLIES',
       'Technology', 'technology', 'furniture', 'office supplies',
       'TECHNOLOGY'], dtype=object)

In [ ]:
import numpy as np
print("Average Sales:", np.mean(df['Sales']))
print("Maximum Sales:", np.max(df['Sales']))
print("Minimum Sales:", np.min(df['Sales']))
print("Median Sales:", np.median(df['Sales']))
print("Sales Standard Deviation:", np.std(df['Sales']))
print("Total Sales:", np.sum(df['Sales']))

Average Sales: 35062.72142925374
Maximum Sales: 9999999.0
Minimum Sales: 1.08
Median Sales: nan
Sales Standard Deviation: 567586.1490108116
Total Sales: 35238035.036400005

## **Manual Data Cleaning**

Manual inspection was performed to identify missing values, duplicate records, inconsistent text formatting, extra spaces, invalid numerical values, outliers, and inconsistent date formats. The dataset was examined using functions such as head(), unique(), describe(), isnull().sum(), and duplicated().sum().

In [ ]:
df.head(20)

,Row ID,Order ID,Order Date,Ship Date,Customer Name,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Darren Powers,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,FURNITURE,Bookcases,261.960,2,0.00,41.9136
1,2,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Consumer,United States,Henderson,Kentucky,42420,south,Furniture,Chairs,731.940,3,0.00,219.5820
2,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
3,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310
4,5,US-2023-141817,01-05-2023,01-12-2023,Mick Brown,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.20,2.5164
5,6,US-2023-167199,01-06-2023,01-10-2023,NaN,Standard Class,Consumer,United States,Los Angeles,California,90032,WEST,Furniture,Furnishings,48.860,7,0.00,14.1694
6,7,US-2023-167199,01-06-2023,01-10-2023,Maria Etezadi,Standard Class,Consumer,United States,Los Angeles,California,90032,West,OFFICE SUPPLIES,Art,7.280,4,0.00,1.9656
7,8,US-2023-106054,01-06-2023,01-07-2023,Jack O'Briant,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.20,90.7152
8,9,US-2023-167199,01-06-2023,01-10-2023,Maria Etezadi,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.504,3,0.20,5.7825
9,10,US-2023-167199,01-06-2023,01-10-2023,Maria Etezadi,Standard Class,Consumer,United States,NaN,California,90032,West,Office Supplies,Appliances,114.900,5,0.00,34.4700
10,11,US-2023-167199,01-06-2023,01-10-2023,Maria Etezadi,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.184,9,0.20,85.3092
11,12,US-2023-130813,01-06-2023,01-08-2023,Lycoris Saunders,Standard Class,Consumer,United States,Los Angeles,California,90032,West,technology,Phones,911.424,4,0.20,68.3568
12,13,US-2023-167199,01-06-2023,01-10-2023,Maria Etezadi,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,15.552,3,0.20,5.4432
13,14,US-2023-167199,01-06-2023,01-10-2023,NaN,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.20,132.5922
14,15,US-2023-105417,01-07-2023,01-12-2023,Vivek Sundaresam,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,68.810,5,0.80,-123.8580
15,16,NaN,01-07-2023,01-12-2023,Vivek Sundaresam,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,2.544,3,0.80,-3.8160
16,17,US-2023-135405,01-09-2023,1/13/2023,Melanie Seite,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,665.880,6,0.00,13.3176
17,18,US-2023-135405,01-09-2023,1/13/2023,Melanie Seite,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,55.500,2,0.00,9.9900
18,19,US-2023-149020,01-10-2023,1/15/2023,NaN,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,8.560,2,0.00,2.4824
19,20,US-2023-149020,01-10-2023,1/15/2023,Anthony Jacobs,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,213.480,3,0.20,16.0110

In [ ]:
df['Region'].unique()

array(['South', 'south', 'West', 'WEST', 'Central', 'East', 'EAST',
       'central', 'SOUTH', 'west'], dtype=object)

In [ ]:
df['Category'].unique()

array(['FURNITURE', 'Furniture', 'Office Supplies', 'OFFICE SUPPLIES',
       'Technology', 'technology', 'furniture', 'office supplies',
       'TECHNOLOGY'], dtype=object)

In [ ]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

In [ ]:
df['Customer Name'].head(20)

0          Darren Powers
1          Phillina Ober
2          Phillina Ober
3          Phillina Ober
4             Mick Brown
5                    NaN
6          Maria Etezadi
7          Jack O'Briant
8          Maria Etezadi
9          Maria Etezadi
10         Maria Etezadi
11      Lycoris Saunders
12         Maria Etezadi
13                   NaN
14      Vivek Sundaresam
15      Vivek Sundaresam
16         Melanie Seite
17         Melanie Seite
18                   NaN
19        Anthony Jacobs
Name: Customer Name, dtype: object

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         2
Order Date       0
Ship Date        0
Customer Name    5
Ship Mode        0
Segment          0
Country          0
City             1
State            2
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            2
Quantity         0
Discount         0
Profit           1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(6)

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,1007.000000,1007.000000,1.005000e+03,1007.000000,1007.000000,1006.000000
mean,499.894737,53604.615690,3.506272e+04,3.797418,0.162989,18.255878
std,289.341026,31522.592965,5.678687e+05,2.265366,0.209113,225.297959
min,1.000000,1841.000000,1.080000e+00,1.000000,0.000000,-3839.990400
25%,250.500000,19805.000000,1.828000e+01,2.000000,0.000000,1.796275
50%,500.000000,50322.000000,5.550000e+01,3.000000,0.200000,8.536600
75%,750.500000,85023.000000,2.131150e+02,5.000000,0.200000,27.256300
max,1000.000000,98661.000000,9.999999e+06,14.000000,0.800000,3177.475000

In [ ]:
df[['Order Date','Ship Date']].head(20)

    Order Date   Ship Date
0   01-03-2023  01-07-2023
1   01-04-2023  01-08-2023
2   01-04-2023  01-08-2023
3   01-04-2023  01-08-2023
4   01-05-2023  01-12-2023
5   01-06-2023  01-10-2023
6   01-06-2023  01-10-2023
7   01-06-2023  01-07-2023
8   01-06-2023  01-10-2023
9   01-06-2023  01-10-2023
10  01-06-2023  01-10-2023
11  01-06-2023  01-08-2023
12  01-06-2023  01-10-2023
13  01-06-2023  01-10-2023
14  01-07-2023  01-12-2023
15  01-07-2023  01-12-2023
16  01-09-2023   1/13/2023
17  01-09-2023   1/13/2023
18  01-10-2023   1/15/2023
19  01-10-2023   1/15/2023

In [ ]:
df['City'].head(20)

0           Henderson
1           Henderson
2         Los Angeles
3     Fort Lauderdale
4     Fort Lauderdale
5         Los Angeles
6         Los Angeles
7         Los Angeles
8         Los Angeles
9                 NaN
10        Los Angeles
11        Los Angeles
12            Concord
13            Seattle
14         Fort Worth
15         Fort Worth
16            Madison
17        West Jordan
18      San Francisco
19      San Francisco
Name: City, dtype: object

In [ ]:
df['Sales'].describe()

count    1.005000e+03
mean     3.506272e+04
std      5.678687e+05
min      1.080000e+00
25%      1.828000e+01
50%      5.550000e+01
75%      2.131150e+02
max      9.999999e+06
Name: Sales, dtype: float64

# **Automatic Data Cleaning**

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         2
Order Date       0
Ship Date        0
Customer Name    5
Ship Mode        0
Segment          0
Country          0
City             1
State            2
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            2
Quantity         0
Discount         0
Profit           1
dtype: int64

In [ ]:
#Fill Missing Order ID
df['Order ID'] = df['Order ID'].fillna(method='ffill')

#Fill Missing Customer Name
df['Customer Name'] = df['Customer Name'].fillna('Unknown')

#Fill Missing City - City is a text column and mode gives the most frequent city.
df['City'] = df['City'].fillna(df['City'].mode()[0])

#Fill Missing State
df['State'] = df['State'].fillna(df['State'].mode()[0])

#Fill Missing Sales - Mean is used because Sales is numerical data.
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())

#Fill Missing Profit
df['Profit'] = df['Profit'].fillna(df['Profit'].mean())

#Remove Extra Spaces from Customer Name
df['Customer Name'] = df['Customer Name'].str.strip()

#Standardize Region Names - Now all becomes : West
df['Region'] = df['Region'].str.title()

#Standardize Category Names
df['Category'] = df['Category'].str.title()

#Remove Duplicate Rows
df = df.drop_duplicates()

#Handle Sales Outliers
df = df[df['Sales'] < 100000]

/tmp/ipykernel_9548/2143843735.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order ID'] = df['Order ID'].fillna(method='ffill')

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Customer Name    0
Ship Mode        0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [ ]:
df['Category'].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [ ]:
#Save Cleaned Dataset
df.to_csv('cleaned_superstore.csv', index=False)

# **The 10 Business Questions & Answers**


# Q1. Which product sub-categories are generating losses despite high sales?

In [39]:
loss_products = df.groupby('Sub-Category')[['Sales','Profit']].sum().reset_index()

loss_products = loss_products[loss_products['Profit'] < 0]

loss_products = loss_products.sort_values(
    by='Sales',
    ascending=False
)

loss_products

   Sub-Category       Sales     Profit
11     Machines  32622.1160 -4951.3543
16       Tables  23519.0290 -3068.9437
4     Bookcases  13834.9904 -1971.6986
15     Supplies   2391.6480  -306.0760



# Q2. Which states are generating the highest sales but lowest profit?

In [40]:
state_analysis = df.groupby('State')[['Sales','Profit']].sum().reset_index()

state_analysis = state_analysis.sort_values(
    by=['Sales','Profit'],
    ascending=[False,True]
)

state_analysis.head(10)

             State         Sales     Profit
3       California  75810.821429  6581.6685
6         Delaware  35605.161429   181.2864
35           Texas  30242.767400 -3772.5734
26        New York  28844.774000  7412.9859
31    Pennsylvania  17029.021000 -4170.8204
16        Michigan  11748.852000  2764.7077
9         Illinois  11340.169000 -1115.7864
27  North Carolina  11263.682000 -3559.7027
38      Washington   9893.644000  2608.7205
7          Florida   8110.505000  -720.3483



# Q3. Which customers are most valuable in terms of both sales and profit?

In [43]:
customer_value = df.groupby('Customer Name')[['Sales','Profit']].sum().reset_index()

customer_value = customer_value[
    (customer_value['Sales'] > customer_value['Sales'].mean()) &
    (customer_value['Profit'] > customer_value['Profit'].mean())
]

customer_value = customer_value.sort_values(
    by=['Sales','Profit'],
    ascending=[False,False]
)

customer_value.head(10)

        Customer Name         Sales     Profit
378      Xylona Preis  36586.231429   366.9088
268  Mitch Willingham   6361.580000  3179.2651
217      Kunst Miller   4806.238000   552.8159
181        Jay Kimmel   4435.638000  1452.3678
324       Ruben Dartt   4029.028000  2005.1826
56         Bruce Geld   3347.370000   636.0003
138   Frank Gastineau   3127.092000  1413.3469
295        Paul Prost   3090.054000   690.1453
171       Jack Lebron   2834.582000  1254.3998
301    Pete Armstrong   2735.952000   341.9940

# Q4. Which shipping mode generates the highest average profit per order?

In [44]:
ship_profit = df.groupby('Ship Mode')['Profit'].mean().reset_index()

ship_profit = ship_profit.sort_values(
    by='Profit',
    ascending=False
)

ship_profit

        Ship Mode      Profit
0     First Class   26.114011
3  Standard Class   20.598912
2    Second Class   20.086091
1        Same Day -166.634671

# Q5. Which category performs best after considering discounts?

In [45]:
category_discount = df.groupby('Category').agg(
    Avg_Discount=('Discount','mean'),
    Total_Profit=('Profit','sum')
).reset_index()

category_discount = category_discount.sort_values(
    by='Total_Profit',
    ascending=False
)

category_discount

          Category  Avg_Discount  Total_Profit
1  Office Supplies      0.163847  12441.140678
2       Technology      0.143085   7177.539100
0        Furniture      0.177330  -1358.988300

# Q6. What percentage of total sales comes from the Top 10 customers?

In [46]:
top10_sales = df.groupby('Customer Name')['Sales'].sum().nlargest(10).sum()

total_sales = df['Sales'].sum()

percentage = (top10_sales / total_sales) * 100

print("Percentage of Sales from Top 10 Customers:", round(percentage, 2), "%")

Percentage of Sales from Top 10 Customers: 37.94 %

# Q7. Which sub-category gives the highest return per unit sold?

In [49]:
df["Return_per_Unit"] = df["Profit"] / df["Quantity"]

result = df.groupby("Sub-Category")["Return_per_Unit"].mean().sort_values(ascending=False)

result.head(10)

Sub-Category
Copiers        182.163400
Chairs          13.706222
Accessories     12.296737
Phones          11.450307
Envelopes        7.842680
Storage          6.583711
Binders          6.559480
Paper            6.075946
Appliances       4.636551
Labels           4.628807
Name: Return_per_Unit, dtype: float64

# Q8. Which customers are the most loyal based on number of orders?

In [50]:
loyal_customers = df.groupby("Customer Name")["Order ID"].count().sort_values(ascending=False)

loyal_customers.head(10)

Customer Name
Kunst Miller           11
Shirley Daniels        10
Sam Craven             10
Jonathan Doherty        9
Marina Lichtenstein     9
Stewart Visinsky        8
Brian Dahlen            8
Chloris Kastensmidt     8
Carol Triggs            8
Xylona Preis            8
Name: Order ID, dtype: int64

# Q9. Which segment is most stable in terms of profit?

In [57]:
segment_stability = df.groupby("Segment")["Profit"].std().sort_values()

segment_stability

Segment
Consumer       119.220091
Corporate      143.907383
Home Office    303.139110
Name: Profit, dtype: float64

# Q10. Which shipping mode is most cost-efficient (high profit, low discount)?

In [58]:
shipping_efficiency = df.groupby("Ship Mode").agg(
    Total_Profit=("Profit", "sum"),
    Avg_Discount=("Discount", "mean")
).reset_index()

shipping_efficiency = shipping_efficiency.sort_values(
    by="Total_Profit",
    ascending=False
)

shipping_efficiency

        Ship Mode  Total_Profit  Avg_Discount
3  Standard Class     5931.1753      0.152235
2    Second Class     1564.6726      0.155000
0     First Class     1472.4700      0.181081
1        Same Day      -15.2384      0.066667